spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taskslist?currentSchema=taskslist
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
     # data-locations: classpath:demo_data.sql

security:
    jwt:
      secret: 'MzRAM1NERkdnZ2dnZyYqJV5eaFAwMDAwMCZeVEZGQ0VTUlhZVlVWVXZ5Y3Z5dGM='
      access: 3600000
      refresh: 2592000000

