spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taskslist?currentSchema=taskslist
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/taskslist?useSSL=false
    #username: root
    #password: root

  sql:
    init:
      mode: never
      continue-on-error: false
      #data-locations: classpath:demo_data2.sql

###########################################

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000
    refresh: 25920000000

