security:
  jwt:
    secret: "d2V0cnl5dWlvb2piaG9vZmR2YmJibm15Zw=="
    access: 1
    refresh: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taskslist?currentSchema=taskslist
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: false
     # data-locations: classpath:demo_data.sql

